name: Cypress CI - Cross-Browser

on:
  push:
    branches: [main]
  workflow_dispatch:
  
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, electron]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Run Cypress with Recording
      run: | 
        npx cypress run \
        --record \
        --key ${{ secrets.CYPRESS_RECORD_KEY }} \
        --ci-build-id ${{ github.run_id }} \
        --group cross-browser-tests-${{matrix.browser}} \
        --browser ${{matrix.browser}} \
        --spec cypress/e2e/trainingTests \
        --tag cross-browser,${{ matrix.browser }}
      env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          COMMIT_INFO_MESSAGE: "Cypress Cross Browser Run"
